backup: vma: add context to error message upon backup start
Upon failure, the queue_execute() function returns the error message
from QEMU directly:

> INFO: issuing guest-agent 'fs-freeze' command
> INFO: issuing guest-agent 'fs-thaw' command
> ERROR: <error message from QEMU>

Many such error messages mention internal QEMU functions and can be
hard to interpret without knowledge of QEMU.

Add some context to the error message to improve this:

> INFO: issuing guest-agent 'fs-freeze' command
> INFO: issuing guest-agent 'fs-thaw' command
> ERROR: executing QMP command to start backup failed - <error message from QEMU>

In case of PBS and provider-based backups, mon_cmd() is used, which
already includes the information which failed QMP command it is, for
example, for PBS:

> ERROR: VM 100 qmp command 'backup' failed - <error message from QEMU>

Signed-off-by: Fiona Ebner <f.ebner@proxmox.com>
Link: https://lore.proxmox.com/20260326113251.68540-2-f.ebner@proxmox.com